name: Android Main Distribute(Firebase)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Firebase Distribute Main (Android)
    runs-on: macos-14
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest changes
        run: |
          git reset --hard
          git pull origin $GITHUB_REF --rebase

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Setup Caching for our Gradle Builds
      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      # More Gradle Caching
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Install Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      # Update our Store Deployment JSON File
      - name: Setup Firebase Deployment JSON File
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" > "${{ github.workspace }}/android/app/firebase-deployment.json"

      # Setup our Android Keystore file
      - name: Setup Keystore File
        run: echo "${{secrets.ANDROID_KEYSTORE_FILE}}" | base64 -d > "${{ github.workspace }}/android/app/quick-do.keystore"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Install fastlane
      - name: Install Fastlane
        run: gem install fastlane

      - name: Add Firebase Distribution plugin
        run: |
          bundle exec fastlane add_plugin firebase_app_distribution

      - name: Run Fastlane Lane for Android App APK
        run: |
          bundle exec fastlane android build_and_distribute_apk_firebase
        env:
          # Signing info
          FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          FIREBASE_TESTER_GROUP_ALIAS: ${{ secrets.FIREBASE_TESTER_GROUP_ALIAS }}
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
